pipeline{
    agent any
    stages{
        stage('Clone repo'){
            steps{
                git branch: 'main', url: 'https://github.com/asadjvd/Jenkins-Projects.git'
            }
        }
        stage('Build image'){
            steps{
                dir('Two-Tier-Flask-App') {
                     sh 'docker build -t flask-app .'
                }
            }
        }
        stage('Deploy with docker compose'){
            steps{
                dir('Two-Tier-Flask-App') {
                // existing container if they are running
                sh 'docker compose down || true'
                // start app, rebuilding flask image
                sh 'docker compose up -d --build'
                }
            }
        }
    }
}
